### ISSUE TITLE
Docs tweaks

### ISSUE THREAD

**Issue by taldcroft** [astropy/saba#6]
- Link to Sherpa should be http://cxc.harvard.edu/contrib/sherpa
- Write installation instructions assuming:
  - https://github.com/astropy/astropy/pull/5241/ is merged to master
  - Saba is available as a pip-installable released package

**Comment by nocturnalastro** [comment]
[Done](http://saba.readthedocs.io/en/latest/)

**Comment by nocturnalastro** [comment]
[Done](http://saba.readthedocs.io/en/latest/)
